### ISSUE TITLE
Linking to Anchor brings error

### ISSUE THREAD

**Issue by svenhe88** [dragdropsite/mPurpose#6]
Hello,
*sorry for bad english, let's give a try ;-)*

im trying to link to an anchor. 
Example: <a href="#home">Home</a>

After I clicked on the link it goes into the area and than directly to the root path. (http://localhost/xampp/test/undefined)
If I type the path (http://localhost/xampp/test/#home) directly in the browser is is working fine.

When I'm disabled the jquery script it works fine. http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js

I don't have enough experience with jquery, can someone give me a hint?

thanks,
Sven

**Comment by aslauris** [comment]
Hi @svenhe88 

I don't think it's related to the theme itself as it doesn't contain any javascript code which is executed on 'link click'. I've just checked it and it works fine. Are you using some custom javascript?

**Comment by svenhe88** [comment]
Thanks for quick answer,
I'm not using any customs. I checked it with the original template and just edited this home link to the anchor #home.
I tried the same link at another place in the html doc. This works fine. Just in the nav tag not.

I deleted the id='mainmenu' at the nav tag at line 52
Now it works fine!!

Can you tell me what this ID has to do?!

thanks,
Sven

**Comment by aslauris** [comment]
Oh, I didn't realise you're using it in nav. There was a small issue - I've updated main-menu.js to solve it.

id='mainmenu' is required to init the menu (dropdown menu won't work without id='mainmenu')

**Comment by svenhe88** [comment]
Thank you very much ;-)
